version: '2'

services:

  datastore:
    image: datastore
    build:
      context: .
      dockerfile: Dockerfile-datastore
    ports:
      - "3301:3301"
    volumes:
      - ./data:/var/lib/tarantool
      - ./:/home/src

  imagehoster:
    image: imagehoster
    build:
      context: .
      dockerfile: Dockerfile-imagehoster
    ports:
      - "80"
    environment:
      - STEEMIT_UPLOAD_STEEMD_WEBSOCKET
      - STEEMIT_UPLOAD_AWS_KEY_ID
      - STEEMIT_UPLOAD_AWS_SECRET_KEY
      - STEEMIT_UPLOAD_TEST_KEY
